version: "3"
services:
  django_app:
    build:
      context: /Users/pavlo/Documents/Python/Django22/
      dockerfile: Dockerfile
    volumes:
      - /Users/pavlo/Documents/Python/Django22/:/app/
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
  redis:
    image: redis:latest
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /Users/pavlo/Documents/Python/Django22/:/app/
    command: celery -A myapp.tasks worker --loglevel=info
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /Users/pavlo/Documents/Python/Django22/:/app/
    command: celery -A myapp.tasks beat --loglevel=info
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: kxigiki
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Pavlo